name: CoptC
options:
  bundleIdPrefix: tr.deadella
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.19"
    CURRENT_PROJECT_VERSION: "41"
targets:
  CoptC:
    type: application
    platform: iOS
    sources:
      - path: CoptC
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tr.deadella.coptc
        INFOPLIST_FILE: CoptC/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Manual
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: minimal
    info:
      path: CoptC/Info.plist
      properties:
        CFBundleDisplayName: CoptC
        UILaunchScreen: {}
        ITSAppUsesNonExemptEncryption: false
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSAppTransportSecurity:
          NSExceptionDomains:
            168.144.210.201:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSExceptionRequiresForwardSecrecy: false
              NSIncludesSubdomains: true
